# Configuração para AMCL e Map Server - Atividade 2

amcl:
  ros__parameters:
    # Parâmetros de movimento do robô
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2

    # Frames de referência
    base_frame_id: "base_footprint"
    global_frame_id: "map"
    odom_frame_id: "odom"

    # Configurações do laser
    laser_model_type: "likelihood_field"
    laser_max_range: 11.0
    laser_min_range: 0.1
    max_beams: 60

    # Configuração do filtro de partículas
    max_particles: 2000
    min_particles: 500
    pf_err: 0.05
    pf_z: 0.99

    # Atualização do filtro
    update_min_a: 0.2
    update_min_d: 0.25
    resample_interval: 1

    # Recuperação de localização
    recovery_alpha_fast: 0.1
    recovery_alpha_slow: 0.001

    # Parâmetros do modelo de sensor
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    sigma_hit: 0.2
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0

    # Configurações de beam skip
    do_beamskip: false
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3

    # Modelo de movimento
    robot_model_type: "nav2_amcl::DifferentialMotionModel"

    # Transformadas
    tf_broadcast: true
    transform_tolerance: 1.0

    # Tópicos
    scan_topic: "/jetauto/lidar/scan"
    map_topic: "map"

    # Pose inicial
    set_initial_pose: false
    always_reset_initial_pose: false
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0

    # Outras configurações
    save_pose_rate: 0.5
    first_map_only: false
    random_seed: -1
    introspection_mode: "disabled"

map_server:
  ros__parameters:
    yaml_filename: ""  # Será passado via linha de comando
    topic_name: "map"
    frame_id: "map"
